# Name of the GitHub Actions workflow
name: Frontend CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # A single job in this workflow called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Define the sequence of tasks that will be executed
    steps:
      # Step 1: Checks-out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up Node.js and enables caching for npm
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      # Step 4: Run the linter
      - name: Lint code
        run: npm run lint
        working-directory: ./client

      # Step 5: Run the production build to catch any build errors
      - name: Build application
        run: npm run build
        working-directory: ./client
        env:
          # Provide a dummy value for the build-time env variable
          NEXT_PUBLIC_API_BASE_URL: http://localhost:3001/api/v1

      # Step 6: Run tests (placeholder for future tests)
      - name: Run tests
        run: npm run test
        working-directory: ./client